name: Add Release Notes to a Release PR

on:
  pull_request:
    branches:
      - releases/v**
    types:
      - opened
      - reopened

jobs:
  changelog:
    name: Release Notes
    runs-on: ubuntu-latest

    steps:
      - uses: daytime-em/release-notes-on-pr@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
