name: Add Release Notes to a Release PR

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - releases/v**

jobs:
  changelog:
    name: Release Notes
    runs-on: ubuntu-latest
    #if: startsWith(github.head_ref, 'releases/v')

    steps:
      - uses: daytime-em/release-notes-on-pr@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
