name: Create Draft Release

on:
  pull_request:
    types: [closed]

jobs:
  draft:
    if: startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Draft a new release with the release notes from PR (TRY GETTING FROM CONTEXT)
    steps:
     - name: Draft a release of (TODO TRY GETTING FROM CONTEXT)
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: ${{ github.ref_name }}
         release_name: ${{ github.ref_name }}
         body: ${{ github.event.pull_request.pull_request.body }}
         draft: true