name: Deploy to Release

on:
  release:
    types:
      - published

jobs:
  echo-it:
    name: Do the echoing
    runs-on: ubuntu-latest

    steps:
      - name: Do we have a branch in the event
        run: echo ${{ github.ref }}
