name: Deploy to Release

on:
  release:
    types:
      - published

jobs:
  echo-it:
    name: Do the echoing
    runs-on: ubuntu-latest

    steps:
      - name: Should only happen when undrafting a release
        run: git branch --show-current
      - name: Try to print a ref too
        run: git rev-parse --short HEAD
      - name: Do we have a branch in the event
        run: echo ${{ github.ref }}
