name: Deploy to Release

on:
  release:
    types:
      - published

jobs:
  echo-it:
    name: Do the echoing
    runs-on: ubuntu-latest

    steps:
      # TODO: Dist Plugin needs to know this is not a dev build & isn't on master.
      # TODO: Maybe we check out master here.
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: What does git branch say
        run: git branch --show-current
      - name: Do we have a branch in the event
        run: echo ${{ github.ref }}
