name: Deploy to Release

on:
  release:
    types:
      - published

jobs:
  echo-it:
    name: Do the echoing
    runs-on: ubuntu-latest

    steps:
      # Need the git repo for muxDistribution to know the branch (uses git cli)
      - uses: actions/checkout@v3
      - name: Do we have a branch in the event
        run: echo ${{ github.ref }}
